config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :pokemons
end

  #   end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
#HomeController est la classe du controleur Home
#Elle herite de ApplicationController

#APplication controller n'est pas un controleur mais une
#classe mere qui herite de ActionController::Base

#Cela permet de factoriser du code
#index est la methode de notre action

class HomeController < ApplicationController
	def index
	end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
	def index
		@pokemons = Pokemon.all
	end

	def show
		@pokemon = Pokemon.find params[:id]
	end

	def new
	end

	def create
	end

	def edit
	end

	def update
	end

	def destroy
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%# commented line %>

<h1>
Ceci est la page d'accueil du projet
<%= Rails.application.class.parent_name %> !
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Pokedex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pokemons/index.html.erb
<h1>Liste des Pokemons</h1>

<p>
	<%= link_to 'Ajouter un Pokemon', new_pokemon_path, class: 'btn btn-success'  %>
</p>

<section class="table-responsive">
	<% if@pokemons.any? %>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<% @pokemons.each do |pokemon| %>
					<tr>
						<td><%= pokemon.id %></td>
						<td><%= pokemon.name %></td>
						<td><%= link_to 'Afficher', pokemon_path(pokemon) %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% else %>
		<p>No data.</p>
	<% end %>
</section>

app/views/pokemons/new.html.erb
<h1>Création d'un Pokemon</h1>

<%= form_for :pokemon do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/pokemons/show.html.erb
<h1>Afficher un pokemon</h1>

<p>N° <%= @pokemon.id %> <%= @pokemon.name %></p>

<p>
	<%= link_to 'Retour', pokemons_path, class: 'btn btn-default' %>
</p>